[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "2qaWbGPrDecc3DaRJR5ZoCgqasQLGnopmyP36dqRVR72"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
