[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
go_fund_me = "J6rEQGR3fFqSHf6TKsRku3r7qmQZ1FHvz7CReoNsczUr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
