[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "HkV1c91adQfR3rsbg4vGhrdYYdGu8NPzFwAmfmA6Cmju"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
