[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
novi_capstone = "AtAZe5QUrvRJvggMvZ8Cmr5mB4N5mgJMR7F4sjJwnZ9t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
