[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "G3P8xEy536E9aqdNtBDzdVxKjdgDefz59EYYR52F5cbr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
